version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"  # Frontend expuesto en el puerto 80
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5000:3000"  # El backend se expone en el puerto 5000 de la máquina
    environment:
      - NODE_ENV=production
    restart: always