version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: always


  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

